实验四/DGJW.Web/Controllers/FilesController.cs
using DGJW.Dal.SysMange;
using DGJW.Model;
using DGJW.Web.Entity;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DGJW.Web.Controllers
{
    public class FilesController : Controller
    {
        public ActionResult Index()
        {
            GDJWContext db = new GDJWContext();
            ViewBag.list = db.FilesSet.ToList();
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

        public ActionResult List()
        {
            GDJWContext db = new GDJWContext();
            ViewData.Model = db.FilesSet.ToList();
            return View();
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public void Create(FilesSet files, HttpPostedFileBase file)
        {
            var fileName = file.FileName;
            var filePath = Server.MapPath("~/File");
            file.SaveAs(Path.Combine(filePath, fileName));

            files.Path = fileName;
            GDJWContext db = new GDJWContext();
            db.FilesSet.Add(files);
            db.SaveChanges();
            db.Dispose();
            Response.Redirect("/Files/List");
        }

        public void Delete(int id)
        {
            GDJWContext db = new GDJWContext();
            var f =db.FilesSet.Find(id);
            if (f!=null)
            {
                db.FilesSet.Remove(f);
                db.SaveChanges();
            }
            Response.Redirect("/Files/List");
        }

        public ActionResult Edit(int id)
        {
            GDJWContext db = new GDJWContext();
            var f = db.FilesSet.Find(id);
            ViewData.Model = f;
            return View();
        }

        [HttpPost]
        public void Edit(FilesSet filesSet)
        {
            GDJWContext db = new GDJWContext();
            db.FilesSet.Update(filesSet);
            db.SaveChanges();
            Response.Redirect("/Files/List");
        }
    }
}

实验四/DGJW.Web/Controllers/NewsViewController.cs
using DGJW.Bll.NewsManage;
using DGJW.Model;
using DGJW.Model.Pager;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DGJW.Web.Controllers
{
    public class NewsViewController :Controller
    {
        NewsBll bll = new NewsBll();
        // GET: News
        public ActionResult Index()
        {
            List<News> newsList = bll.Query(n=>n.IsRec==2).ToList();
            ViewBag.newsList = newsList;
            return View();
        }

        public ActionResult IndexByPage(int index)
        {
            List<News> newsList = bll.Query(n => n.IsRec == 2).ToList();
            newsList = newsList.Skip(3 * index).Take(3).ToList();
            var count = bll.Query().Count();
            PageOfList<News> newsPageList = new PageOfList<News>(newsList, index, 3, count);
            ViewBag.newsPageList = newsPageList;
            ViewBag.key = null;
            return View("~/Views/NewsView/_NewsListPart.cshtml");
        }


        public ActionResult IndexBySearch(string key,int index)
        {
            var list = bll.Query(n => n.IsRec == 2).Where((n)=>n.Keyword.Contains(key)||n.Title.Contains(key));
            List<News> newsList = new List<News>();
            if (list!=null)
            {
                newsList = list.ToList();
            }
            var count = newsList.Count();
            newsList = newsList.Skip(3 * index).Take(3).ToList();
            PageOfList<News> newsPageList = new PageOfList<News>(newsList,index, 3, count);
            ViewBag.newsPageList = newsPageList;
            ViewBag.key = key;
            return View("~/Views/NewsView/_NewsListPart.cshtml");
        }

        public ActionResult New(Int64 Id)
        {
            News news = bll.Find(Id);
            ViewBag.news = news;
            news.Hits++;
            bll.SaveChanges();
            return View();
        }

    }
}

实验四/DGJW.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - 我的 ASP.NET 应用程序</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("应用程序名称", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("主页", "Index", "Home")</li>
                    <li>@Html.ActionLink("新闻", "Index", "NewsView")</li>
                    <li>@Html.ActionLink("文件", "Index", "Files")</li>
                    <li>@Html.ActionLink("登录", "Index", "Admins/Auth")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - @@版权所有xxxx</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

实验四/DGJW.Web/Views/Shared/_MyLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - 本科教育服务网</title>
    <link rel="stylesheet" href="~/Content/bootstrap.min.css" /> 
    @Scripts.Render("~/bundles/modernizr")

</head>
<body class="container">
    <header class="row">
        <div class=" col-md-11">
            <h1>本科教育服务网</h1>
            <p>管理员，欢迎你</p>
            <ul class="nav nav-pills " style="padding:8px 0px">
                <li role="presentation" class="active"><a href="/Admins/Home/Index">个人首页</a></li>
                <li role="presentation" class="active"><a href="/News/Create">新闻发布</a></li>
                <li role="presentation" class="active"><a href="/News/News">新闻管理</a></li>
                <li role="presentation" class="active"><a href="/Files/Create">文件上传</a></li>
                <li role="presentation" class="active"><a href="/Files/List">文件管理</a></li>
            </ul>
        </div>
    </header>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - <a href="/Admins/Auth/Index">@@版权所有xxxx</a></p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>